### ISSUE TITLE
update.py: import collections from ase python package ...

### ISSUE THREAD

**Issue by miroi** [coderefinery/autocmake#182]
Hi Rado,

I have python 2.7.3 but I can not do autocmake module update due to missing python module. What is missing there ? The server is pretty packed with up-to-date software, but one never knows what is missing...

~~~
milias@lxi079.gsi.de:~/Work/qch/software/small_projects/mathlibs-tester/cmake/.python ./update.py --help
Traceback (most recent call last):
  File "./update.py", line 7, in <module>
    import collections
  File "/u/milias/Work/qch/projects/ase/build/lib.linux-x86_64-2.7/ase/collections/__init__.py", line 1, in <module>
    from ase.collections.collection import Collection
ImportError: No module named ase.collections.collection
milias@lxi079.gsi.de:~/Work/qch/software/small_projects/mathlibs-tester/cmake/.python -V
Python 2.7.3
milias@lxi079.gsi.de:~/Work/qch/software/small_projects/mathlibs-tester/cmake/.python ./update.py ..
Traceback (most recent call last):
  File "./update.py", line 7, in <module>
    import collections
  File "/u/milias/Work/qch/projects/ase/build/lib.linux-x86_64-2.7/ase/collections/__init__.py", line 1, in <module>
    from ase.collections.collection import Collection
ImportError: No module named ase.collections.collection
~~~

**Comment by miroi** [comment]
Closing ... I messed it with ase package, after deleting it all works.
